db{
    dbUrl = "jdbc:sqlserver://192.168.20.122:1433;databaseName=Amps;encrypt=true;trustServerCertificate=true"
    dbUser = "sa"
    dbPassword = "Srimant@9"
    dbDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}

amps{
    host = "192.168.20.52"
    port = 9007
    topicTradesRaw = "trades.raw"
    topicTradesEnriched = "trades.enriched"
    topicTradesValidated = "trades.validated"
    topicTradesFigured = "trades.figured"
}
