db{
    dbUrl = "jdbc:sqlserver://localhost:1433;databaseName=hari;encrypt=true;trustServerCertificate=true"
    dbUser = "sa"
    dbPassword = "harish@02"
    dbDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}

amps{
    host = "192.168.20.52"
    port = 9007
    topicTradesRaw = "trades.raw"
    topicTradesEnriched = "trades.enriched"
    topicTradesValidated = "trades.validated"
}